### ISSUE TITLE
pom文件里面的文件影响外面的程序

### ISSUE THREAD

**Issue by lilaizhencn** [IamFive/spring-data-jdbcx#2]
pom引用的spring boot logging ，logjdbc  影响外部程序的log4j2配置。会导致不能打印。还有一大堆没用的比如postgre。。找bug找了好几个小时，终于排查到了。

**Comment by IamFive** [comment]
有些是可以设置成 <optional>true</optional> ，我等闲了改一下。但是影响到外部不太可能，你项目中的log全部要改成用 slf4j 的接口，slf4j会自动桥接到项目路径下的log实现。

log4jdbc 是用来 log sql的，非常好用，项目里有配置的例子，把配置文件拷贝过去就可以了。
spring-boot-starter-logging 是用来桥接所有的Log到slf4j的。

**Comment by IamFive** [comment]
Tag 2.0.2 发布了，log只留了logback+slf4j。其他的不需要的改成optional了，这样如果项目中需要，需要自己引入。

等明天有空了我会发到maven center

**Comment by lilaizhencn** [comment]
哈哈哈  我的项目吧spring-boot-starter-logging排除了。用的slf4j log4j2桥接。
